[package]
name = "mc_assembly"
version = "0.1.0"
edition = "2024"

[dependencies]
clipboard = "0.5.0"
colored = "3.0.0"
once_cell = "1.21.3"
regex = "1.12.2"
tempfile = "3.23.0"

[[bin]]
name="cui"
path="src/cui.rs"
